// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/kakkky/kakkky.dev/adapter/client"
	"github.com/kakkky/kakkky.dev/adapter/handler"
	"github.com/kakkky/kakkky.dev/adapter/middleware"
	"github.com/kakkky/kakkky.dev/adapter/query"
	"github.com/kakkky/kakkky.dev/adapter/repository"
	"github.com/kakkky/kakkky.dev/config"
	"github.com/kakkky/kakkky.dev/driver/db"
	"github.com/kakkky/kakkky.dev/driver/httpserver"
	"github.com/kakkky/kakkky.dev/usecase"
)

// Injectors from wire.go:

func InitServer(ctx context.Context, cfg *config.Config) (*Server, func(), error) {
	sqlxDB, cleanup, err := db.NewDB(ctx, cfg)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := repository.NewRepository(sqlxDB)
	queryService := query.NewQueryService(sqlxDB)
	clientClient := client.NewClient(cfg)
	useCase := usecase.NewUseCase(repositoryRepository, queryService, clientClient)
	handlerHandler := handler.NewHandler(cfg, useCase)
	middlewareMiddleware := middleware.NewMiddleware(cfg)
	httpHandler := httpserver.NewMux(cfg, handlerHandler, middlewareMiddleware)
	httpServer := httpserver.NewHTTPServer(cfg, httpHandler)
	server := NewServer(httpServer)
	return server, func() {
		cleanup()
	}, nil
}
