// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/kakkky/kakkky.dev/adapter/handler"
	"github.com/kakkky/kakkky.dev/adapter/middleware"
	"github.com/kakkky/kakkky.dev/adapter/repository"
	"github.com/kakkky/kakkky.dev/config"
	"github.com/kakkky/kakkky.dev/driver/db"
	"github.com/kakkky/kakkky.dev/driver/httpserver"
)

// Injectors from wire.go:

func InitServer(ctx context.Context) (*Server, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	sqlxDB, cleanup, err := db.NewDB(ctx, configConfig)
	if err != nil {
		return nil, nil, err
	}
	repositoryRepository := repository.NewRepository(sqlxDB)
	handlerHandler := handler.NewHandler(repositoryRepository)
	middlewareMiddleware := middleware.NewMiddleware()
	httpHandler := httpserver.NewMux(handlerHandler, middlewareMiddleware)
	httpServer := httpserver.NewHTTPServer(configConfig, httpHandler)
	server := NewServer(httpServer)
	return server, func() {
		cleanup()
	}, nil
}
