// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/kakkky/kakkky.dev/adapter/handler"
	"github.com/kakkky/kakkky.dev/adapter/middleware"
	"github.com/kakkky/kakkky.dev/config"
	"github.com/kakkky/kakkky.dev/driver/httpserver"
)

// Injectors from wire.go:

func InitServer() (*Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	handlerHandler := handler.NewHandler()
	middlewareMiddleware := middleware.NewMiddleware()
	httpHandler := httpserver.NewMux(handlerHandler, middlewareMiddleware)
	httpServer := httpserver.NewHTTPServer(configConfig, httpHandler)
	server := NewServer(httpServer)
	return server, nil
}
