version: "2"

linters:
  settings:
    errcheck:
      exclude-functions:
        - (io.Closer).Close
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - (github.com/yuin/goldmark/util.BufWriter).WriteString
