// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Header() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<header class=\"sticky top-0 z-10 border-b border-gray-200 bg-white/80 backdrop-blur\"><div class=\"mx-auto max-w-4xl px-6 h-14 flex items-center justify-between\"><a href=\"/feed\" class=\"flex items-center gap-2\"><span class=\"inline-flex h-7 w-7 items-center justify-center rounded-md bg-gray-900 text-white text-xs font-bold\">k</span> <span class=\"text-sm font-semibold tracking-tight\">kakkky.dev</span></a><nav class=\"flex items-center gap-6 text-sm text-gray-700\"><a href=\"/feed\" class=\"hover:text-gray-900\">Feed</a> <span class=\"h-4 w-px bg-gray-200\" aria-hidden=\"true\"></span> <a href=\"/rss.xml\" aria-label=\"RSS\" class=\"text-gray-500 hover:text-gray-900\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"18\" height=\"18\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M4 11a9 9 0 0 1 9 9\"></path> <path d=\"M4 4a16 16 0 0 1 16 16\"></path> <circle cx=\"5\" cy=\"19\" r=\"1\"></circle></svg></a></nav></div></header>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
