// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../testhelper/mock/mock_client.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	io "io"
	reflect "reflect"

	domain "github.com/kakkky/kakkky.dev/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// NewOGPFetcher mocks base method.
func (m *MockClient) NewOGPFetcher() domain.OGPFetcher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewOGPFetcher")
	ret0, _ := ret[0].(domain.OGPFetcher)
	return ret0
}

// NewOGPFetcher indicates an expected call of NewOGPFetcher.
func (mr *MockClientMockRecorder) NewOGPFetcher() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewOGPFetcher", reflect.TypeOf((*MockClient)(nil).NewOGPFetcher))
}

// NewS3Client mocks base method.
func (m *MockClient) NewS3Client() domain.S3Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewS3Client")
	ret0, _ := ret[0].(domain.S3Client)
	return ret0
}

// NewS3Client indicates an expected call of NewS3Client.
func (mr *MockClientMockRecorder) NewS3Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewS3Client", reflect.TypeOf((*MockClient)(nil).NewS3Client))
}

// MockS3Client is a mock of S3Client interface.
type MockS3Client struct {
	ctrl     *gomock.Controller
	recorder *MockS3ClientMockRecorder
	isgomock struct{}
}

// MockS3ClientMockRecorder is the mock recorder for MockS3Client.
type MockS3ClientMockRecorder struct {
	mock *MockS3Client
}

// NewMockS3Client creates a new mock instance.
func NewMockS3Client(ctrl *gomock.Controller) *MockS3Client {
	mock := &MockS3Client{ctrl: ctrl}
	mock.recorder = &MockS3ClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Client) EXPECT() *MockS3ClientMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockS3Client) Upload(ctx context.Context, contentType string, body io.Reader) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, contentType, body)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockS3ClientMockRecorder) Upload(ctx, contentType, body any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockS3Client)(nil).Upload), ctx, contentType, body)
}

// MockOGPFetcher is a mock of OGPFetcher interface.
type MockOGPFetcher struct {
	ctrl     *gomock.Controller
	recorder *MockOGPFetcherMockRecorder
	isgomock struct{}
}

// MockOGPFetcherMockRecorder is the mock recorder for MockOGPFetcher.
type MockOGPFetcherMockRecorder struct {
	mock *MockOGPFetcher
}

// NewMockOGPFetcher creates a new mock instance.
func NewMockOGPFetcher(ctrl *gomock.Controller) *MockOGPFetcher {
	mock := &MockOGPFetcher{ctrl: ctrl}
	mock.recorder = &MockOGPFetcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOGPFetcher) EXPECT() *MockOGPFetcherMockRecorder {
	return m.recorder
}

// Fetch mocks base method.
func (m *MockOGPFetcher) Fetch(ctx context.Context, url string) (domain.OGPData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Fetch", ctx, url)
	ret0, _ := ret[0].(domain.OGPData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Fetch indicates an expected call of Fetch.
func (mr *MockOGPFetcherMockRecorder) Fetch(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockOGPFetcher)(nil).Fetch), ctx, url)
}
