// Code generated by MockGen. DO NOT EDIT.
// Source: query_service.go
//
// Generated by this command:
//
//	mockgen -source=query_service.go -destination=../testhelper/mock/mock_query_service.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/kakkky/kakkky.dev/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockQueryService is a mock of QueryService interface.
type MockQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockQueryServiceMockRecorder
	isgomock struct{}
}

// MockQueryServiceMockRecorder is the mock recorder for MockQueryService.
type MockQueryServiceMockRecorder struct {
	mock *MockQueryService
}

// NewMockQueryService creates a new mock instance.
func NewMockQueryService(ctrl *gomock.Controller) *MockQueryService {
	mock := &MockQueryService{ctrl: ctrl}
	mock.recorder = &MockQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueryService) EXPECT() *MockQueryServiceMockRecorder {
	return m.recorder
}

// NewFeedQueryService mocks base method.
func (m *MockQueryService) NewFeedQueryService() domain.FeedQueryService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewFeedQueryService")
	ret0, _ := ret[0].(domain.FeedQueryService)
	return ret0
}

// NewFeedQueryService indicates an expected call of NewFeedQueryService.
func (mr *MockQueryServiceMockRecorder) NewFeedQueryService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewFeedQueryService", reflect.TypeOf((*MockQueryService)(nil).NewFeedQueryService))
}

// MockFeedQueryService is a mock of FeedQueryService interface.
type MockFeedQueryService struct {
	ctrl     *gomock.Controller
	recorder *MockFeedQueryServiceMockRecorder
	isgomock struct{}
}

// MockFeedQueryServiceMockRecorder is the mock recorder for MockFeedQueryService.
type MockFeedQueryServiceMockRecorder struct {
	mock *MockFeedQueryService
}

// NewMockFeedQueryService creates a new mock instance.
func NewMockFeedQueryService(ctrl *gomock.Controller) *MockFeedQueryService {
	mock := &MockFeedQueryService{ctrl: ctrl}
	mock.recorder = &MockFeedQueryServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedQueryService) EXPECT() *MockFeedQueryServiceMockRecorder {
	return m.recorder
}

// ListFeedItems mocks base method.
func (m *MockFeedQueryService) ListFeedItems(ctx context.Context, afterID domain.FeedItemID, afterPublishedAt time.Time, limit int) ([]domain.FeedItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListFeedItems", ctx, afterID, afterPublishedAt, limit)
	ret0, _ := ret[0].([]domain.FeedItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListFeedItems indicates an expected call of ListFeedItems.
func (mr *MockFeedQueryServiceMockRecorder) ListFeedItems(ctx, afterID, afterPublishedAt, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListFeedItems", reflect.TypeOf((*MockFeedQueryService)(nil).ListFeedItems), ctx, afterID, afterPublishedAt, limit)
}
